# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: 'dmx-simples-CI'

trigger:
  branches:
   include:
       - master
  paths:
   include:
       - '**/*.java'
       - pom.xml
       - azure-pipelines.yml

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to Staging Directory' 
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/target/'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Package'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dmx-simples'
    publishLocation: 'Container'

- task: GitHubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: BrunoDPO
    repositoryName: BunoDPO/dmx-simples
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
